### ISSUE TITLE
LICENSE.termcolor doesn't exist

### ISSUE THREAD

**Issue by SuperWig** [p-ranav/csv2#10]
https://github.com/p-ranav/csv2/blob/68ded29a7af0d6660afc41fb96677462e42578e2/CMakeLists.txt#L56

I believe this is a copy and paste error and is meant to be `LICENSE.mio`?

**Comment by p-ranav** [comment]
Indeed a copy-paste error. Thanks for reporting.

**Comment by SuperWig** [comment]
Damn that was *fast* 👍
