### ISSUE TITLE
Read a single cell. Can you provide sample

### ISSUE THREAD

**Issue by sergioferrari** [p-ranav/csv2#12]
Hello Pranav,
can you provide an example of how to read the contents of a single cell? 
How to extract the contents that can be a string, an int or a double?
I share the request of Amirmasoudabdol, that is to be able to access each cell to read/write the content.
Thank you very much.
Sergio

**Comment by p-ranav** [comment]
As you know from #9, this project does not yet have a csv writer. I'll work on this soon, once I find the time. 

As for the reader, are you asking how to get the contents of cells? Some clarifications:

* The CSV reader does not support random access, e.g., `my_csv[14][3]`. This is a consequence of the implementation - The reader does not perform any string copies during the parsing.
* You can iterate over the cells and construct your own `std::vector<std::map<std::string, std::string>>` for all the rows in the table.

Iteration looks like below. Use `.read_value()` to read the value of the cell - This involves a string copy. 

```cpp
    for (const auto row: csv) {
      for (const auto cell: row) {
        // Do something with cell value
        std::string value;
        cell.read_value(value);
        // Now you have the cell value
        // You can insert this into an std::map for use later 
      }
    }
```

**Comment by sergioferrari** [comment]
Thank you so much for your answer.
