### ISSUE TITLE
Quote character is not getting parsed

### ISSUE THREAD

**Issue by remz1337** [p-ranav/csv2#14]
Hello,

I have copy pasted the default example to read a CSV file into variable which works fine, but the quote characters are not removed with `std::string value; cell.read_value(value);`

My dev environment:
OS: Windows 10
Compiler: MSVC 2019

example csv:
a,b,c
"Hello", 0.123, "World"

**Comment by p-ranav** [comment]
Hmmm I don't have a Windows machine to test with. On my Macbook, it seems to work fine:

```cpp
#include "csv2.hpp"
#include <iostream>
using namespace	csv2;

int main() {
  Reader<delimiter<','>,
	 quote_character<'"'>,
	 first_row_is_header<false>,
	 trim_policy::trim_whitespace> csv;

  if (csv.mmap("example.csv")) {
    for (const auto row: csv) {
      for (const auto cell: row) {
	// Do something with cell value
	std::string value;
	cell.read_value(value);
        std::cout << value << "\n";
      }
    }
  }
}
```

```csv
a,b,c
"Hello", 0.123, "World"
```

```console
$ ./main
a
b
c
"Hello"
0.123
"World"
```

Can you tell me what you see when you run the above program?

**Comment by remz1337** [comment]
Hmm, I thought the quote characters were supposed to be remove, so the actual content of my string variable would be `Hello` and not `"Hello"`, but I might be mistaken.

If that is the intended behaviour, I guess I can work around with some basic string manipulation. It would be nice to have this has an option in your parser.

Thanks

**Comment by p-ranav** [comment]
Currently, this is in the intended behavior. I'll look to set this up as an option in the future.
