### ISSUE TITLE
could you make a package? (tag/release)

### ISSUE THREAD

**Issue by wanghenshui** [p-ranav/csv2#23]
it's easy integrate with xmake package management
good for cmake fetchcontent management, too

example https://github.com/xmake-io/xmake-repo/blob/master/packages/a/abseil/xmake.lua

i already write a config, if you made the package, i send this PR to xmake repo
`package("csv2")
    set_urls("https://github.com/p-ranav/csv2.git")
    set_homepage("https://github.com/p-ranav/csv2")
    set_description("A CSV parser library")
    set_license("MIT")
    // add_version()

    on_install(function (package)
        os.cp("include/csv2", package:installdir("include"))
    end)
    on_test(function (package)
        assert(package:has_cxxtypes("csv2::Reader<csv2::delimiter<','>, csv2::quote_character<'\"'>, csv2::first_row_is_header<false>>", 
        {configs = {languages = "c++11"}, includes = "csv2/reader.hpp"}))
    end)
package_end()`

**Comment by p-ranav** [comment]
Hello. Thanks for your request. 

I've created a release [here](https://github.com/p-ranav/csv2/releases/tag/v0.1).

**Comment by wanghenshui** [comment]
cool
