### ISSUE TITLE
Compiler error due to C++17 feature being used

### ISSUE THREAD

**Issue by CodeFinder2** [p-ranav/csv2#42]
The library is declared as being C++11 compatible. Unfortunately, in one of the recent commits f18b1dc, a C++17 feature has been used:
https://github.com/p-ranav/csv2/commit/f18b1dc4142f76f85d7bca203898e42a22dfe4f9#diff-11cb52805aba3ae1bec78f314ffd50874111a067ca9662de968ede56cce18337R44

g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) complains:
```
include/csv2/writer.hpp:35: Fehler: constexpr if is a C++17 extension [-Werror,-Wc++17-extensions]
    if constexpr (has_close<Stream, void()>::value) {
       ^
```

Would love to see a fix for this (which should be simple). :-)

**Comment by p-ranav** [comment]
Fixed, thanks for reporting this.
